version: '3'
services:
  web:
    image: docker.genya0407.net/asahi:v0.1-rc3
    command: /go/bin/asahi-series-feeder --port=3000
    ports:
      - "127.0.0.1:${HOST_PORT:?err}:3000"
    restart: always
